config/routes.rb
Rails.application.routes.draw do
  resources :answers
  resources :questions
  root 'home#index'

  get '/about' => 'home#about'

  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/answer.rb
class Answer < ApplicationRecord

	include HasGravatar
	belongs_to :question

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/concerns/has_gravatar.rb
module HasGravatar

	def gravatar
		"https://secure.gravatar.com/avatar/#{Digest::MD5.hexdigest(email.downcase)}"
	end

end

app/models/question.rb
class Question < ApplicationRecord

	include HasGravatar
	has_many :answers
	
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController

	def create
		question = Question.find(params[:answer][:question_id]) #Find the question with this question_id
		answer = question.answers.create(answer_params) #Find the answers of this question and create another answer with answer_params

		MainMailer.notify_question_author(answer).deliver_later

		session[:current_user_email] = answer_params[:email] #Save users email into session
		redirect_to question #Redirect to the page of that question
	end

	private

	def answer_params
		params.require(:answer).permit(:email, :body) #Requires an answer object and allows 2 params
	end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  	@questions = Question.order(created_at: :desc).all
  end

  def about
  end

  def temp
  	redirect_to root_path
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController

	def show
		@question = Question.find(params[:id])

		@answers = @question.answers.order(created_at: :desc)
	end

	def create
		Question.create(question_params)
		session[:current_user_email] = question_params[:email] #Save users email into session
		redirect_to root_path
	end

	private

	def question_params
		params.require(:question).permit(:email, :body)
	end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper

	def current_user_email
		session[:current_user_email]
	end

end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/home/_navbar.html.erb
	<nav class="navbar navbar-expand-md navbar-dark bg-dark">
	  	<a class="navbar-brand" href="/">
	   	 	History of the Universe
	  	</a>
	  	<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    		<span class="navbar-toggler-icon"></span>
  		</button>

  		<div class="collapse navbar-collapse justify-content-end" id="navbarSupportedContent">
		  	<ul class="navbar-nav">
		  		<li class="nav-item user-email-wrapper">
		  			<div class="navbar-text nav-user-email"><%= current_user_email %></div>
		  		</li>
	  			<li class="nav-item">
	  				<a href="#" class="btn btn-success navbar-btn btn-sm" data-toggle="modal" data-target="#new-question-modal">Ask a question</a>
	  			</li>
	  		</ul>
  		</div>
	</nav>

app/views/home/_new_answer_form.html.erb
<div class="modal fade" id="new-answer-modal" tabindex="-1" role="dialog">
  	<div class="modal-dialog" role="document">
	    <div class="modal-content">
	      <div class="modal-header">
	        <h5 class="modal-title">New Answer</h5>
	        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
	          <span aria-hidden="true">&times;</span>
	        </button>
	      </div>
	      <%= form_for :answer, url: '/answers' do %>
	      <!-- <form action="/questions" method="POST"> -->
	      		<input type="hidden" name="answer[question_id]" value="<%= @question.id %>">
		      	<div class="modal-body">
				  <div class="form-group">
				    <label for="inputEmail">Email address</label>
				    <input type="email" name="answer[email]" class="form-control" value="<%= current_user_email %>" id="inputEmail" aria-describedby="emailHelp" placeholder="Email" required>
				  </div>
				  <div class="form-group">
				    <label for="inputQuestion">Answer</label>
				    <textarea class="form-control" name="answer[body]" id="inputQuestion" rows="3" placeholder="What is your answer?" required></textarea>
				  </div>
		      </div>

		      <div class="modal-footer">
		        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
		        <button type="submit" class="btn btn-primary">Submit</button>
		      </div>
	      <% end %>
	    </div>
  	</div>
</div>

app/views/home/_new_question_form.html.erb
<div class="modal fade" id="new-question-modal" tabindex="-1" role="dialog">
  	<div class="modal-dialog" role="document">
	    <div class="modal-content">
	      <div class="modal-header">
	        <h5 class="modal-title">New Question</h5>
	        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
	          <span aria-hidden="true">&times;</span>
	        </button>
	      </div>
	      <%= form_for :question, url: '/questions' do %>
	      <!-- <form action="/questions" method="POST"> -->
		      <div class="modal-body">
				  <div class="form-group">
				    <label for="inputEmail">Email address</label>
				    <input type="email" name="question[email]" class="form-control" value="<%= current_user_email %>" id="inputEmail" aria-describedby="emailHelp" placeholder="Email" required>
				  </div>
				  <div class="form-group">
				    <label for="inputQuestion">Question</label>
				    <textarea class="form-control" name="question[body]" id="inputQuestion" rows="3" placeholder="What would you like to know" required></textarea>
				  </div>
		      </div>

		      <div class="modal-footer">
		        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
		        <button type="submit" class="btn btn-primary">Submit</button>
		      </div>
	      <% end %>
	    </div>
  	</div>
</div>

app/views/home/about.html.erb
<h1>About us</h1>

app/views/home/index.html.erb
<div class="jumbotron">
		<h3>The Universe is the totality of everything that exists, has existed, or ever will exist.</h3>
		<p>This Q&A site is dedicated to questions about the history of the Universe</p>
</div>

<div class="container">
	<% @questions.each do |q| %>
		<div class="boxes">
			<div class="media question" data-target="<%= question_path(q) %>">
				<img class="mr-3" src="<%= q.gravatar %>">
				<div class="media-body">
					<h5 class="mt-0"><%= q.email %> asked:</h5>
					<div class="time d-none d-md-block"><%= time_ago_in_words q.created_at %> ago</div>
					<div><%= truncate q.body, length: 300 %></div>
					<div>
						<a href="<%= question_path(q) %>" class="btn btn-success btn-sm view-answers d-none d-md-block">View Answers (<%= q.answers.count %>)</a>
					</div>
				</div>
			</div>
		</div>
	<% end %>


	<% if @questions.empty? %>
		<div class="alert alert-primary">Nothing here yet, be the first to ask?</div>
	<% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>History of the Universe</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
	
	 <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

  </head>

  <body>

  <%= render 'home/navbar' %>
	<%= render 'home/new_question_form' %>

  <div class="container">
    <%= yield %>
  </div>
  </body>
</html>

app/views/questions/show.html.erb
<div class="lead card card-body bg-light">
	<div class="media">
  		<img class="mr-3" src="<%= @question.gravatar %>" alt="Users image">
  		<div class="media-body">
    		<h5 class="mt-0"><%= @question.email %> asked:</h5>
    		<%= @question.body %>
  		</div>
	</div>
</div>

<div class="container">
	<div class="row">
		<div class="col">
			<div>
				<button type="button" class="btn btn-success btn-sm new-answer-btn" data-toggle="modal" data-target="#new-answer-modal">Submit new answer</button>
			</div>
			<%= render '/home/new_answer_form' %>
			<% @answers.each do |answer| %>
				<div class="media border answers-b">
					<img class="mr-3" src="<%= answer.gravatar %>" alt="Users image">
					<div class="media-body">
						<h5 class="mt-0"><%= answer.email %> answered:</h5>
						<%= time_ago_in_words answer.created_at %> ago<br>
						<%= answer.body %>
					</div>
				</div>
			<% end %>
			<% if @answers.empty? %>
				<div class="alert alert-primary">No answers yet, want to help a fellow colleague?</div>
			<% end %>
		</div>
	</div>
</div>